name: protein_gibbs_sampler
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
dependencies:
  - python>=3.9,<3.10
  - pandas>=1.3.5,<2.0.0
  - muscle~=3.8.0
  - biopython~=1.79
  - tqdm
  - pytorch~=2.5.0
  - pytorch-cuda=12.4
  - mafft=7.487
  - hmmer~=3.3.2
  - pip
  - pytest
  - pytest-datadir
  - pip:
    - git+https://github.com/facebookresearch/esm.git
    - -e .

