TOKENIZERS_PARALLELISM=false python run_mlm.py \
    --tokenizer_name Rostlab/prot_bert_bfd \
    --cache_dir /workspace/cache/hf_transformers \
    --train_file /workspace/data/tautomerase_2953_train.fasta \
    --validation_file /workspace/data/tautomerase_2953_val.fasta \
    --overwrite_cache \
    --max_seq_length 110 \
    --preprocessing_num_workers 8 \
    --mlm_probability 0.15 \
    --line_by_line \
    --output_dir /workspace/src/training/mlm-train-bert-single/results \
    --do_train \
    --do_eval \
    --do_predict \
    --evaluation_strategy epoch \
    --prediction_loss_only \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 64 \
    --learning_rate 3e-05 \
    --weight_decay 0.0 \
    --adam_beta1 0.9 \
    --adam_beta2 0.999 \
    --adam_epsilon 1e-8 \
    --num_train_epochs 150 \
    --warmup_steps 200 \
    --logging_dir /workspace/src/training/mlm-train-bert-single/logs \
    --logging_first_step \
    --logging_steps 200 \
    --save_total_limit 3 \
    --seed 3 \
    --dataloader_num_workers 8 \
    --run_name mlm-train-bert-single-taut \
    --load_best_model_at_end \
    --metric_for_best_model eval_loss \
    --overwrite_output_dir