TOKENIZERS_PARALLELISM=false python run_plm.py \
    --model_name_or_path Rostlab/prot_xlnet \
    --cache_dir /workspace/cache/hf_transformers \
    --train_file /workspace/data/Russ_994_random_train.fasta \
    --validation_file /workspace/data/Russ_994_random_val.fasta \
    --overwrite_cache \
    --max_seq_length 110 \
    --preprocessing_num_workers 8 \
    --line_by_line \
    --output_dir /workspace/src/training/plm-finetuner-xlnet/results \
    --do_train \
    --do_eval \
    --do_predict \
    --evaluation_strategy epoch \
    --prediction_loss_only \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 8 \
    --learning_rate 3e-05 \
    --weight_decay 0.0 \
    --adam_beta1 0.9 \
    --adam_beta2 0.999 \
    --adam_epsilon 1e-8 \
    --num_train_epochs 100 \
    --warmup_steps 1000 \
    --logging_dir /workspace/src/training/plm-finetuner-xlnet/logs \
    --logging_first_step \
    --logging_steps 200 \
    --save_total_limit 3 \
    --fp16 \
    --fp16_opt_level '02' \
    --seed 3 \
    --dataloader_num_workers 8 \
    --run_name plm-finetuner-xlnet-taut \
    --load_best_model_at_end \
    --metric_for_best_model eval_loss \
    --overwrite_output_dir